---
# Default GitHub labels
- color: d73a4a
  name: bug
  description: Something isn't working
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: New feature or request
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: 008672
  name: help wanted
  description: Extra attention is needed
- color: e4e669
  name: invalid
  description: This doesn't seem right
- color: d876e3
  name: question
  description: Further information is requested
- color: ffffff
  name: wontfix
  description: This will not be worked on

# Labels specific to cloudalchemy
- color: 0366d6
  name: area/docs
  description: Improvements or additions to documentation
- color: 0366d6
  name: area/tests
  description: Everything related to molecule tests and linters
- color: 0366d6
  name: area/automation
  description: CI configurations
- color: 43fa79
  name: area/chore
  description: langage and tooling related
- color: 692060
  name: area/api
  description: Grpc api related
- color: 4e6c8e
  name: area/web
  description: Ui related
- color: 18718a
  name: area/cmd
  description: Command line related
- color: 140784
  name: area/lib
  description: Core libraries related
- color: facce3
  name: area/networks
  description: Concerning a network module
- color: 34cb03
  name: area/brokers
  description: Concerning a broker module
- color: 55e0fc
  name: area/telegram
  description: Concerning tg bots
- color: 989793
  name: area/ide
  description: Ide config related

